### ISSUE TITLE
Spigot changed internal method breaking JeffLib.

### ISSUE THREAD

**Issue by andrewkm** [mfnalex/JeffLib#23]
https://gist.githubusercontent.com/andrewkm/ea20686c3e0fa8b5445c209c6f8666f0/raw/52f8c095f4d4941e0ee759e0f518472e4acacc41/gistfile1.txt

**Comment by andrewkm** [comment]
@mfnalex anything that can be done about this?

**Comment by mfnalex** [comment]
A pull request :p im still in clinic for a few days but I can merge any pr if someone creates one

**Comment by andrewkm** [comment]
Ah alright, will wait until you are better and hope all is well with your health! :)

**Comment by andrewkm** [comment]
@mfnalex would you have some time to take a look at this one now?

**Comment by andrewkm** [comment]
@mfnalex looks like I'm getting this now: 
`[WARNING] The POM for com.allatori:allatori-annotations:jar:8.5 is missing, no dependency information available`
`[ERROR] Failed to execute goal on project jefflib-nms-generic: Could not resolve dependencies for project com.jeff-media.jefflib:jefflib-nms-generic:jar:13.0.0-SNAPSHOT: Could not find artifact com.allatori:allatori-annotations:jar:8.5 in jeff-media-gbr (https://hub.jeff-media.com/nexus/repository/jeff-media-public/) -> [Help 1]`

Any ideas why It's not building for us?

**Comment by mfnalex** [comment]
Update the dependency for "allatori-annotations" from 8.6 to 8.5, which should be in my public repo. 

It's a shame that allatori doesn't provide it in their own repo. I'll email them to get it available to everyeone. Until then, just downgrade to 8.5 and it should work just fine.

**Comment by mfnalex** [comment]
I have now asked allatori for permission to either host latest on my own repo, or for them to finally publish sone. Now gotta wait for an answer ( they usually answer within 1-2 days ). Thanks for your patianece.

**Comment by andrewkm** [comment]
Really appreciate it, thanks! :)

**Comment by mfnalex** [comment]
If going from 8.6 to 8.5 does not fix your current issue, please let me know again.

**Comment by andrewkm** [comment]
> If going from 8.6 to 8.5 does not fix your current issue, please let me know again.

We haven't forked to check tbh, we're just waiting on the allatori issue to get fixed instead.
Assuming they haven't answered yet?

**Comment by mfnalex** [comment]
> > If going from 8.6 to 8.5 does not fix your current issue, please let me know again.
> 
> We haven't forked to check tbh, we're just waiting on the allatori issue to get fixed instead. Assuming they haven't answered yet?

JeffLib uses version 8.4 of allatori annotations IIRC. I have now just uploaded it to my public repository without having waited for the answer. I don't think it's an issue as they provide the download publicly anyway. So this issue should be fixed now

**Comment by andrewkm** [comment]
> > > If going from 8.6 to 8.5 does not fix your current issue, please let me know again.
> > 
> > 
> > We haven't forked to check tbh, we're just waiting on the allatori issue to get fixed instead. Assuming they haven't answered yet?
> 
> JeffLib uses version 8.4 of allatori annotations IIRC. I have now just uploaded it to my public repository without having waited for the answer. I don't think it's an issue as they provide the download publicly anyway. So this issue should be fixed now

I seem to still be getting:

`[ERROR] Failed to execute goal on project jefflib-nms-generic: Could not resolve dependencies for project com.jeff-media.jefflib:jefflib-nms-generic:jar:13.0.0-SNAPSHOT: Could not find artifact com.allatori:allatori-annotations:jar:8.5 in jeff-media-gbr (https://hub.jeff-media.com/nexus/repository/jeff-media-public/) -> [Help 1]`

**Comment by andrewkm** [comment]
@mfnalex https://github.com/mfnalex/JeffLib/blob/8275fa3322c933220b55e4813dcd97f78113ed1a/nms/generic/pom.xml#L43 ?

**Comment by mfnalex** [comment]
Oh yeah my bad. Either change the version of allatori-annotations to 8.4 or 8.6. both versions are available in my public repository

**Comment by andrewkm** [comment]
@mfnalex would you be able to change it here on this repo?
We do not have it forked and prefer to use yours as it's continuously updated.

**Comment by mfnalex** [comment]
> @mfnalex would you be able to change it here on this project? We do not have it forked and prefer to use yours as it's continuously updated.

Not needed anymore. I have now also uploaded version 8.5 of the annotations to my repository so after doing `mvn clean -U` it should work.

**Comment by andrewkm** [comment]
@mfnalex thank you for uploading, however we are now back to the original issue in this report. The spigot methods. It continues to not compile due to that.

**Comment by andrewkm** [comment]
Thanks! :)

**Comment by andrewkm** [comment]
@mfnalex any updates on this one?

**Comment by andrewkm** [comment]
Finally all solved.
